server:
  port: 8080
spring:
#数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/library?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: tw900516


#mybatis的相关配置
mybatis:
#mapper配置文件
  type-aliases-package: com.example.demo.enity
#开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true